version = 0.1

[default.deploy.parameters]
stack_name = "zuno-backend"
resolve_s3 = true
s3_prefix = "zuno-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "PineconeApiKey=\"pcsk_2AVRSi_6RoqFbXuV9ybygtR5EG3z5R2QK1Yane3jLBWBeQfrDK5Pp8xFLMu3VbPtGzbs2W\" PineconeIndexName=\"zuno\" PineconeEnvironment=\"us-east-1\" GeminiApiKey=\"AIzaSyAFhir9xj2uiioIBoQ15Gu_dFDqbuMxrfU\""
image_repositories = ["RegisterFunction=180294195362.dkr.ecr.us-east-1.amazonaws.com/zunobackend3681d397/registerfunction65985c8brepo", "ChatFunction=180294195362.dkr.ecr.us-east-1.amazonaws.com/zunobackend3681d397/chatfunctiondddd4012repo", "EmbeddingFunction=180294195362.dkr.ecr.us-east-1.amazonaws.com/zunobackend3681d397/embeddingfunction600c53bcrepo", "ScrapingFunction=180294195362.dkr.ecr.us-east-1.amazonaws.com/zunobackend3681d397/scrapingfunction3de197a2repo"]
